
name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request: # When a pull request is made...
    branches:  main  # ... targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up JDK 8
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    # Build with Maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

      # Publie les résultats de test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
          files: target/**/*.xml
